### ISSUE TITLE
Home.vue index Page

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/foodouken.com#103]
Your mission, should you choose to accept: 

Create a home page for foodouken 
![image](https://user-images.githubusercontent.com/5694308/79065222-fac1b380-7cd8-11ea-929c-128a0f4f052c.png)

The design file is [here](https://www.figma.com/file/Q671pbdFk3omco20xmxk5o/foodouken.com?node-id=1866%3A22820)

It has 2 major parts: 
- [ ] Header 
- [ ] Restaurant Cards #102 

# Header 
The header is identical to the current desktop and mobile format 
![image](https://user-images.githubusercontent.com/5694308/79065238-23e24400-7cd9-11ea-8844-ecb8eaea9d75.png)
![image](https://user-images.githubusercontent.com/5694308/79065349-cdc1d080-7cd9-11ea-94a1-9dacde3a07cc.png)

## Content 
Header Title: Foodouken
Subhead: Food delivery for Siem Reap 
Text: 
Foodouken was made in a weekend hackathon at Why Not Earth in Siem Reap, Cambodia as a way to support our wonderful resturaunt owners, an integral part of our community.

# Restaurant Cards 
![image](https://user-images.githubusercontent.com/5694308/79065354-dfa37380-7cd9-11ea-8691-751308d00a0d.png)
The restaurant card list is a list of the #102 restaurant cards, one for all of our restaurants, that allows people to view all available restaurant options

**Comment by GerardBalaoro** [comment]
What's the API endpoint for the data in this page?

**Comment by paulchrisluke** [comment]
We need to add tenent info into our database, I will do that tonight. I think you should be able to expect that info from here when its ready:

https://stagingapi.whynot.earth/api/v0/pages/slug/foodouken

@ctyar can you confirm?

**Comment by atharva3010** [comment]
Home.vue is reserved for the restaurant’s page right now

**Comment by paulchrisluke** [comment]
we should rename the index to home and name the store pages store or tenent to avoid confusion. I'll get data added in tonight and update the issue

**Comment by ctyar** [comment]
No, it will be:
`https://stagingapi.whynot.earth/api/v0/pages/slug/foodouken/home`

**Comment by paulchrisluke** [comment]
@GerardBalaoro : 

https://stagingapi.whynot.earth/api/v0/pages/slug/foodouken/bang-bang-bakery-cafe/shop
and
https://stagingapi.whynot.earth/api/v0/pages/slug/foodouken/georges-rhumerie-and-restaurant/shop

**Comment by ctyar** [comment]
Tenants list:
https://stagingapi.whynot.earth/api/v0/companies/foodouken/tenants

**Comment by paulchrisluke** [comment]
@ctyar should we be expecting a root page like https://stagingapi.whynot.earth/api/v0/companies/foodouken/

or would we use 

https://stagingapi.whynot.earth/api/v0/pages/slug/foodouken/ ?

Note, that page is not updated with correct data

**Comment by ctyar** [comment]
What do you mean by a root page? What do you expect it to do?
`https://stagingapi.whynot.earth/api/v0/companies/foodouken/` We don't have this
`https://stagingapi.whynot.earth/api/v0/pages/slug/foodouken/ ` This returns all the `foodouken` pages

**Comment by paulchrisluke** [comment]
adding missing image asset for @GerardBalaoro 

https://res.cloudinary.com/whynotearth/image/upload/v1587200887/foodouken/foodouken_no_bg_avatar_round_oszzyn.png
