### ISSUE TITLE
cards resize height responsively. Card height should remain the same

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/foodouken.com#107]
product cards currently resize based on screen size. Seomtimes our product pictures are square, rectange, portrait. Sometimes text is weirdly spaced. Cards should maintain the same aspect ratio as designed

https://www.figma.com/file/Q671pbdFk3omco20xmxk5o/foodouken.com?node-id=1245%3A57965

**Comment by sally** [comment]
@paulchrisluke Could you produce instructions on reproducing this bug, please?

**Comment by kbventures** [comment]
This issue has been addressed in # https://github.com/whynotearth/foodouken.com/pull/126

I am requesting we close this one.
