### ISSUE TITLE
Use meredith-core data

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/foodouken.com#11]
design file:
https://www.figma.com/file/Q671pbdFk3omco20xmxk5o/foodouken.com?node-id=1245%3A57965

live url:

https://foodouken.com

## Request:
Right now, the current site is using placeholder data for items like product name, price. We want to use data provided by meredith-core.

The data has already been added, which you can see here:

https://docs.google.com/spreadsheets/d/11yCxusIrtTrTploYqE7llVR-PYjQwhYY-XxQaPJus-o/edit?pli=1#gid=550121964

Browse to pages, filter the category column by company 9 (foodouken), and you will be able to see every page for the foodouken site like it is in our design file above. 

Looking at the slug column will show you the url's of the endpoints meredith-core creates, like this example:

https://stagingapi.whynot.earth/api/v0/pages/slug/foodouken/apple-crumble

by changing the `apple-crumble` to any other slug in that data sheet like `carrot-cake` , you can see any product:

https://stagingapi.whynot.earth/api/v0/pages/slug/foodouken/carrot-cake

## category pages

category page data is also available in the same method, example:

https://stagingapi.whynot.earth/api/v0/pages/slug/foodouken/cakes-and-cookies

## expected result

in the end, foodouken.com should show live data from meredith-core

**Comment by rgostic** [comment]
We can't filter the category column by company 9 (foodouken) because /categories returns an array of { id, title } objects. I have to hard code the start index and stop index.

**Comment by paulchrisluke** [comment]
@Legacylemons , the category `featuredImage` in our category pages is incorrect. It should be the individual picture of the category, like this:
![image](https://user-images.githubusercontent.com/5694308/78414725-b2a2f100-7647-11ea-957f-4ec5e005bbee.png)
please crop each category picture down to individual size, upload to cloudinary, and replace in the database. Let me know when you're done and I'll update production.

**Comment by rgostic** [comment]
Also the ID values in the database are not consistent. When querying /categories the values are 16-22, when querying /category they range from 205-211.

**Comment by rgostic** [comment]
We are also missing product images for the categories:
- bages-and-breads
- cream-cheese-bagels
- coffee-and-tea
- other-drinks

**Comment by rgostic** [comment]
The category `bagels-and-bread` has two products with the same id.

**Comment by paulchrisluke** [comment]
@Legacylemons 
- remove products json from the category pages
- take ID out of custom json for all product pages
