### ISSUE TITLE
refactor to meredith-core schema

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/foodouken.com#117]
In order to properly scale foodouken, we are moving to a better API structure provided by meredith-core.

Instead of craming everything into a single JSON field, which could cause massive scaling problems, we've split out all relevant data here. The following endpoints are an example of company foodouken, with tenant bangbangbakery (1).

Home page API is pending, other endpoints found here:

https://stagingapi.whynot.earth/api/v0/tenant/1/categories
https://stagingapi.whynot.earth/api/v0/tenant/1/categories/16/products

**Comment by paulchrisluke** [comment]
I'm adding this to meredith-core project board for @ctyar tracking of making the home page endpoint. . Should come *after* volkswagen stuff.

**Comment by ctyar** [comment]
The page endpoint for tenants is ready
GET ​`/api​/v0​/pages​/slug​/{companySlug}​/{tenantSlug}/{pageSlug}`

**Comment by paulchrisluke** [comment]
https://stagingapi.whynot.earth/api/v0/tenants/bang-bang-bakery-cafe/categories/
https://stagingapi.whynot.earth/api/v0/tenants/bang-bang-bakery-cafe/categories/16/products

@GerardBalaoro would you be able to help refactor our product pages on the front end ?

**Comment by GerardBalaoro** [comment]
@paulchrisluke What are the updated API endpoints, so I can begin the refactor?

**Comment by paulchrisluke** [comment]
@GerardBalaoro 

Shop Page: https://stagingapi.whynot.earth/api/v0/pages/slug/foodouken/bang-bang-bakery-cafe/shop

Categories held in shop: https://stagingapi.whynot.earth/api/v0/tenants/bang-bang-bakery-cafe/categories/

products within a category: https://stagingapi.whynot.earth/api/v0/tenants/bang-bang-bakery-cafe/categories/16/products
