### ISSUE TITLE
Cart Component

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/foodouken.com#13]
This is the cart component that is present in every page
![image](https://user-images.githubusercontent.com/5694308/78328317-15917b00-75a9-11ea-82f8-393fd3c0adc6.png)
![image](https://user-images.githubusercontent.com/5694308/78328331-1e824c80-75a9-11ea-8c17-14b8a9454802.png)

The cart starts out empty when people are browsing the menu on the site 
![image](https://user-images.githubusercontent.com/5694308/78347671-0c190a80-75cb-11ea-9de6-2ef28e6b8331.png)

Everytime someone presses the plus button on the menu item 
![image](https://user-images.githubusercontent.com/5694308/78347605-f1469600-75ca-11ea-818f-66d227130ed2.png)

The items get added to the cart and the price amount is displayed accordingly 
![image](https://user-images.githubusercontent.com/5694308/78347751-24892500-75cb-11ea-8f73-63948b7e8a7c.png)

They can also add more with the buttons available 
![image](https://user-images.githubusercontent.com/5694308/78347788-310d7d80-75cb-11ea-9e83-357c5c699fc5.png)

## Mobile 

# Design File
For design reference, please see files in [Figma](https://www.figma.com/file/Q671pbdFk3omco20xmxk5o/foodouken.com?node-id=1245%3A57965)

**Comment by paulchrisluke** [comment]
still need to do the empty state cart

**Comment by sally** [comment]
Link to asset in empty state cart: https://res.cloudinary.com/whynotearth/image/upload/v1586099571/foodouken/heart-1x_axcey4.png (1x); https://res.cloudinary.com/whynotearth/image/upload/v1586099572/foodouken/heart-2x_uyh5qv.png (2x)

**Comment by sally** [comment]
> still need to do:
> 
> 1. empty state cart
> 2. add `x` button top left of product image so users can clear the item.
>    ![cancel](https://user-images.githubusercontent.com/5694308/78502437-65c83300-778b-11ea-9571-bf41e2bf9f16.png)

I think I'll also still need to make `Subtotal` and `Order Total` populate correctly, I'll leave `Delivery Fee`  blank for now though.

**Comment by paulchrisluke** [comment]
Please set the delivery fee to static $1 and calculate

**Comment by paulchrisluke** [comment]
@atharva3010 set the delivery fee to static and calculated. This issue is complete, great contribution @sally  we love you
