### ISSUE TITLE
setup staging environment

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/foodouken.com#131]
so we can toggle between staging and production. 

api need to be merged into production, and we should setup a staging.foodouken.com subdomain for testing. use staging api there

**Comment by paulchrisluke** [comment]
@atharva3010 is setting up the front end side right now, I need to schedule a big migration with @ctyar at some point, but will come after more major api changes

**Comment by atharva3010** [comment]
@paulchrisluke we just need to change the API url in netlify env variables and app will start using prod api.

**Comment by paulchrisluke** [comment]
staging setup complete on front end, will move this back into todo when our api is ready.
