### ISSUE TITLE
iOS users cannot complete order 

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/foodouken.com#141]
iOS users cannot complete order 
![image0 (1)](https://user-images.githubusercontent.com/5694308/79756299-a5268000-8344-11ea-898f-8e919ba08cfe.jpg)

We are having auth issues with iOS
It does not allow the cookie to be set
But Bearer token is not working either
I am seeing 401 error
https://stagingapi.whynot.earth/api/v0/authentication/ping
https://stagingapi.whynot.earth/api/v0/tenants/georges-rhumerie-and-restaurant/reservations
The user can register, we get 200, but then the ping and reservation show 401

Ping:

General:
Request URL:https://stagingapi.whynot.earth/api/v0/authentication/ping
Request Method:GET
Status Code:401 

Response headers:
Access-Control-Allow-Credentials:true
Access-Control-Allow-Origin:https://deploy-preview-139--competent-carson-c183df.netlify.app
cf-cache-status:DYNAMIC
cf-ray:586f3a145bbeeff9-EWR
cf-request-id:023962a0b90000eff9750e9200000001
Date:Mon, 20 Apr 2020 13:31:39 GMT
expect-ct:max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server:cloudflare
Set-Cookie:__cfduid=dff1997e5dbb0291d2804b702cb6cb53a1587389499; expires=Wed, 20-May-20 13:31:39 GMT; path=/; domain=.whynot.earth; HttpOnly; SameSite=Lax; Secure
Www-Authenticate:Bearer
x-powered-by:ASP.NET

Request headers:
Accept:application/json, text/plain, */*
Authorisation:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlbWFpbGF0aGFydmFzaGFybWFAZ21haWwuY29tIiwianRpIjoiMGU2ODRkMWItNzBmMS00YTJjLTljMDctYTRjMTJiMmQ2NDU5IiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiIxMTIiLCJleHAiOjE1ODk5ODE0NjMsImlzcyI6InN0YWdpbmdhcGkud2h5bm90LmVhcnRoIiwiYXVkIjoic3RhZ2luZ2FwaS53aHlub3QuZWFydGgifQ.JM-rCfqBgPad4NckrTmRlkfltmkmzQBTbfuICBMfifo
Origin:https://deploy-preview-139--competent-carson-c183df.netlify.app
Referer:https://deploy-preview-139--competent-carson-c183df.netlify.app/shop/georges-rhumerie-and-restaurant
User-Agent:Mozilla/5.0 (iPhone; CPU iPhone OS 13_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1
For reservation,
General:
Request URL:https://stagingapi.whynot.earth/api/v0/tenants/georges-rhumerie-and-restaurant/reservations
Request Method:POST
Status Code:401 

Response headers:
Access-Control-Allow-Credentials:true
Access-Control-Allow-Origin:https://deploy-preview-139--competent-carson-c183df.netlify.app
cf-cache-status:DYNAMIC
cf-ray:586f3a19fd19eff9-EWR
cf-request-id:023962a43d0000eff975150200000001
Date:Mon, 20 Apr 2020 13:31:40 GMT
expect-ct:max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server:cloudflare
Set-Cookie:__cfduid=d801bd2b23091a3cf68f7ff1af6c659e31587389500; expires=Wed, 20-May-20 13:31:40 GMT; path=/; domain=.whynot.earth; HttpOnly; SameSite=Lax; Secure
Www-Authenticate:Bearer
x-powered-by:ASP.NET

Request headers:
Accept:application/json, text/plain, */*
Authorisation:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlbWFpbGF0aGFydmFzaGFybWFAZ21haWwuY29tIiwianRpIjoiMGU2ODRkMWItNzBmMS00YTJjLTljMDctYTRjMTJiMmQ2NDU5IiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiIxMTIiLCJleHAiOjE1ODk5ODE0NjMsImlzcyI6InN0YWdpbmdhcGkud2h5bm90LmVhcnRoIiwiYXVkIjoic3RhZ2luZ2FwaS53aHlub3QuZWFydGgifQ.JM-rCfqBgPad4NckrTmRlkfltmkmzQBTbfuICBMfifo
Content-Type:application/json;charset=utf-8
Origin:https://deploy-preview-139--competent-carson-c183df.netlify.app
Referer:https://deploy-preview-139--competent-carson-c183df.netlify.app/shop/georges-rhumerie-and-restaurant
User-Agent:Mozilla/5.0 (iPhone; CPU iPhone OS 13_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1

Payload:
{"orders":[{"name":"Creole","count":1,"price":4.5}],"subTotal":4.5,"deliveryFee":1,"amount":5.5,"deliveryDateTime":"2020-04-24T08:30:00.000Z","paymentMethod":"ABA Bank Transfer","message":""}

**Comment by atharva3010** [comment]
Fixed
