### ISSUE TITLE
Tenant Site - Business Info

### ISSUE THREAD

**Issue by paigefreeman271** [whynotearth/foodouken.com#164]
# Design File
The specs for page can be found in the [Figma design file](https://www.figma.com/file/Q671pbdFk3omco20xmxk5o/foodouken.com?node-id=2887%3A1)

For the design and the flow, go to the Tenant CMS page

Your mission, should you accept, includes these tasks: 

- [ ] 1. [Top Navigation ](#top-navigation) 
- [ ] 2. [Text Input](#text-input) 
- [ ] 2. [Button](#button) 

![image](https://user-images.githubusercontent.com/5694308/81388095-f951a280-9141-11ea-9e65-e542e3960182.png)

<h1 id="top-navigation">1. Top Navigation</h1> 

![image](https://user-images.githubusercontent.com/5694308/81388129-05d5fb00-9142-11ea-9700-ee50afb71d7a.png)

Title: Business Info
Back Icon: Leads to My Business

## Text Style
Title: 
```
/* Mobile H2 */

font-family: Open Sans;
font-style: normal;
font-weight: bold;
font-size: 24px;
line-height: 33px;
display: flex;
align-items: center;
```

## Colors 
Top Nav Bar Background: Primary (#437784, 100%)
Title: On Primary, High Emphasis (#FFFFFF, 100%)

##Assets 

<h1 id="text-input">2. Text Input</h1> 

![image](https://user-images.githubusercontent.com/63047208/80354461-f97bb380-88a0-11ea-9d66-e63ecc5ab592.png)

## Content 
Text Field:

Text Field Label: 1: Name
Text Field Label 2: Phone Number
Text Field Label 3: Email
Tect Field Label 4: Description

Text Field Floating Label:

Text Field Floating Label 1: Name
Text Field Floating Label 2: Phone Number
Text Field Floating Label 3: Email
Text Field Floating Label 4: Description

## Text Style
Label, Text Field Label: 
```
/* Mobile Body */

font-family: Open Sans;
font-style: normal;
font-weight: normal;
font-size: 16px;
line-height: 22px;
display: flex;
align-items: center;
```

Text Field Floating Label: 
```
/* Mobile Caption */

font-family: Open Sans;
font-style: normal;
font-weight: normal;
font-size: 12px;
line-height: 16px;
```

## Color 
Text Field: On Background Disabled (#FFFFFF, 54%) 
Text Field Floating Label: On Surface Medium (#FFFFFF, 54%)

<h1 id="button">3. Button</h1> 

![image](https://user-images.githubusercontent.com/5694308/81388588-af1cf100-9142-11ea-8879-2224bdafb4a1.png)

## Content 
Button Text: Save Info (Save edited information, return to My Business #148 ) 

## Color
Button Background; Secondary (#0E9EC2)
Button Text: On Secondary, High Emphasis (#FFFFFF, 84%) 

## Text Style 
Button Text:
```
/* Mobile Color Label */

font-family: Open Sans;
font-style: normal;
font-weight: 600;
font-size: 14px;
line-height: 19px;
text-transform: uppercase;
```

**Comment by paulchrisluke** [comment]
PR: https://github.com/whynotearth/foodouken.com/pull/204
