### ISSUE TITLE
Tenant Site - Business Hours

### ISSUE THREAD

**Issue by paigefreeman271** [whynotearth/foodouken.com#165]
# Design File
The specs for page can be found in the [Figma design file]
https://www.figma.com/file/Q671pbdFk3omco20xmxk5o/foodouken.com?node-id=2887%3A1

For the design and the flow, go to theTentant CMS page

Your mission, should you accept, includes these tasks: 

- [ ] 1. [Top Navigation ](#top-navigation) 
- [ ] 2. [Selection](#selection) 

![image](https://user-images.githubusercontent.com/63047208/80357330-08fcfb80-88a5-11ea-826a-31015a21f453.png)

<h1 id="top-navigation">1. Top Navigation</h1> 

![image](https://user-images.githubusercontent.com/63047208/80357679-86c10700-88a5-11ea-9334-67d6caeee6a8.png)

Title: Business Hours
Back Icon: Leads to My Business

This component is here:
https://github.com/whynotearth/foodouken.com/blob/staging/src/components/BaseAppBarHeader.vue

<h1 id="selection">2. Selection</h1> 

![image](https://user-images.githubusercontent.com/63047208/80357972-f0d9ac00-88a5-11ea-9a95-d939d9696914.png)

## Content 

Selection 1: Monday {{Business hours}}
Selection 2: Tuesday {{Business hours}}
Selection 3: Wednesday {{Business hours}}
Selection 4: Thursday {{Business hours}}
Selection 5: Friday {{Business hours}}
Selection 6: Saturday {{Business hours}}
Selection 7: Sunday {{Business hours}}

## Text Style
Text Selection:
```
/* Mobile Body */

font-family: Open Sans;
font-style: normal;
font-weight: normal;
font-size: 16px;
line-height: 22px;
display: flex;
align-items: center;
```

Text Preview: 
```
/* Mobile Body */

font-family: Open Sans;
font-style: normal;
font-weight: normal;
font-size: 16px;
line-height: 22px;
display: flex;
align-items: center;
```

## Color 
Text Selection: On Secondary High Emphasis (#FFFFFF, 87%) 
Text Preview: On Background Medium Emphasis (#FFFFFF, 54%)

**Comment by bamboochow** [comment]
# Mobile Hour Selection Card 
On desktop, the hour selection is presented as a pop-up card. That behavior should be mirrored in mobile but at the moment mobile's pop-up card is covered underneath the top navigation so it cannot close the time selection card 
![image](https://user-images.githubusercontent.com/14948326/90641251-35c18e00-e25b-11ea-9eb8-bd65454a28be.png)

What we want instead for mobile is the pop-up card full screen that users are able to close with the icon to show the business hours screen 
![image](https://user-images.githubusercontent.com/14948326/90642309-6a821500-e25c-11ea-861d-ab81bb0ca329.png)

# Desktop Spacing 
The current spacing on desktop's content should match the spacing of desktop business hours signup just to keep things consistent 
![image](https://user-images.githubusercontent.com/14948326/90642518-addc8380-e25c-11ea-9df7-88665b1f7764.png)
![image](https://user-images.githubusercontent.com/14948326/90642863-1deb0980-e25d-11ea-9dcd-58d95b38a7ea.png)

# Mobile Spacing 
The left screenshot is the deploy preview and the right is our designs. Can you make the text line up properly with the icons? 
![image](https://user-images.githubusercontent.com/14948326/90644147-9acab300-e25e-11ea-9592-7385ea1785f6.png)
