### ISSUE TITLE
Tenant Site - Order Ticket Component

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/foodouken.com#171]
# Design File
For design reference, please see files in [Figma](https://www.figma.com/file/Q671pbdFk3omco20xmxk5o/foodouken.com?node-id=1245%3A57965)

You can find the designs for this issue in the "Tenant Site" Page of Figma 

# Order Ticket Component
Your mission, should you choose to accept: 
This is the order ticket component for an upcoming order. On tap, the card opens #195 Order Detail page for that order
![image](https://user-images.githubusercontent.com/5694308/81389470-14bdad00-9144-11ea-94f6-3e2ca9a3698b.png)

- [ ] 1. [Customer Info](#customer-info)
- [ ] 2. [Ordered Item](#ordered-item)
- [ ] 3. [Special Request/Total](#special-request)
- [ ] 4. [Text Button](#text-button)

<h1 id="customer-info">1. Customer Info</h1> 

![image](https://user-images.githubusercontent.com/5694308/81791742-4f9f5680-9531-11ea-83ad-852331d51e2f.png)

## Content
Name: {{ Customer Name }} 
Phone Icon: (On tap, call customer)

## Color 
Card: 1 dp - Dark Mode Overlay (#003037, 100%  + FFFFFF, 5%)
Icons: Primary (#437784)
Name: On Surface, High emphasis (#FFFFFF, 84%) 
Divider: On Surface, Divider (#FFFFFF, 12%) 

## Text Style 
Name:
```
/* Mobile Caption */

font-family: Open Sans;
font-style: normal;
font-weight: normal;
font-size: 12px;
line-height: 16px;
```

## Shadow 
Card: 
```
/* 1 dp */

background: #C4C4C4;
box-shadow: 0px 1px 3px rgba(0, 0, 0, 0.2), 0px 2px 2px rgba(0, 0, 0, 0.12), 0px 0px 2px rgba(0, 0, 0, 0.14);
```

<h1 id="ordered-item">2. Ordered Item</h1> 

![image](https://user-images.githubusercontent.com/5694308/81792259-07ccff00-9532-11ea-951c-a6342d598914.png)

## Content 
Item name: {{ Item Name }} 
Item Count: {{ Number of this item ordered }} 
Selection option: {{ any additional variation and customizations }} 

## Color
Item name, count: On Surface, High Emphasis (#FFFFFF, 84%) 
Selection Options: 
   - add item customization highlight: Secondary (#0E9EC2, 65%)
   - add item customization text: On Secondary, High emphasis (#FFFFFF, 84%)
   - remove item customization highlight: Error (#ED4A2B, 65%)
   - remove item customization text: On Error, High Emphasis (#FFFFFF, 84%)

## Text Style 
Item Name: 
```
/* Mobile Body */

font-family: Open Sans;
font-style: normal;
font-weight: normal;
font-size: 16px;
line-height: 22px;
```

Item Count: 
```
/* Mobile H3 */

font-family: Open Sans;
font-style: normal;
font-weight: bold;
font-size: 18px;
line-height: 25px;
```

Selection Option: 
```
/* Mobile Caption */

font-family: Open Sans;
font-style: normal;
font-weight: normal;
font-size: 12px;
line-height: 16px;
```
<h1 id="special-request">3. Special Request / Total</h1> 
![image](https://user-images.githubusercontent.com/5694308/81797487-0eab4000-9539-11ea-99a7-f7c142098369.png)

## Content 
Title 1: Special Requests 
Text: {{ Customer Special Request }} 
Title 2: Total 
Price: {{ Total Price }} 

## Color 
Divider: On Surface, High Emphasis (#FFFFFF, 84%) 
Title, Price: On Surface, High Emphasis (#FFFFFF, 84%) 
Text: On Surface, Medium Emphasis (#FFFFFF, 54%) 

## Text Style 
Titles, Price: 
```
/* Mobile Body */

font-family: Open Sans;
font-style: normal;
font-weight: normal;
font-size: 16px;
line-height: 22px;
```

Text: 
```
/* Mobile Caption */

font-family: Open Sans;
font-style: normal;
font-weight: normal;
font-size: 12px;
line-height: 16px;
```

<h1 id="text-button">4. Text Button</h1> 

![image](https://user-images.githubusercontent.com/5694308/81798681-84fc7200-953a-11ea-87ea-31877b98ba4d.png)

## Content 
Text Button: Out For Delivery (Moves order from "upcoming orders" to "in progress" page) 

## Text Style 
Text button: 
```
/* Mobile Color Label */

font-family: Open Sans;
font-style: normal;
font-weight: 600;
font-size: 14px;
line-height: 19px;
text-transform: uppercase;
```

## Color 
Text Button: Secondary (#0E9EC2)

**Comment by bamboochow** [comment]
@abdullahcalisir12 I am setting up our next milestone for this project, what is the status for this issue?

**Comment by abdullahcalisir12** [comment]
ui completed, needs backend support to fetch real data. @bamboochow
