### ISSUE TITLE
Tenant Site - Create Delivery Ticket Component 

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/foodouken.com#179]
# Design File
For design reference, please see files in [Figma](https://www.figma.com/file/Q671pbdFk3omco20xmxk5o/foodouken.com?node-id=1245%3A57965)

You can find the designs for this issue in the "Tenant Site" Page of Figma 

# Delivery Ticket Component 
Your mission, should you choose to accept: 
This is the ticket component for an order that is in progress. On tap, this card opens the #195 Order Detail page 
![image](https://user-images.githubusercontent.com/5694308/81805986-0574a000-9546-11ea-8f7b-de4c8d9caabb.png)

# Customer Info 
![image](https://user-images.githubusercontent.com/5694308/81806151-466cb480-9546-11ea-8ff5-d15ac1e0df19.png)

## Content 
Name: {{ Customer Namee }}
Phone: (On Tap, call customer) 
Address: {{ Customer Address }} 
Map Preview: {{ Google Maps Preview of Location. Opens Google Maps on tap }} 

## Text Style 
Name: 
```
/* Mobile Body */

font-family: Open Sans;
font-style: normal;
font-weight: normal;
font-size: 16px;
line-height: 22px;
```

Address: 
```
/* Mobile Caption */

font-family: Open Sans;
font-style: normal;
font-weight: normal;
font-size: 12px;
line-height: 16px;
```

## Color
Card Background: 1 dp Dark Mode Overlay (#003037, 100% + FFFFFF, 5%) 
Icon Call Button: Secondary (#0E9EC2)
Name, Address: On Surface, High Emphais (#FFFFFF, 84%) 

## Shadow
Card Background: 
```
/* 1 dp */

background: #C4C4C4;
box-shadow: 0px 1px 3px rgba(0, 0, 0, 0.2), 0px 2px 2px rgba(0, 0, 0, 0.12), 0px 0px 2px rgba(0, 0, 0, 0.14);
```

# Order Info
![image](https://user-images.githubusercontent.com/5694308/81806245-643a1980-9546-11ea-8a57-da90fb433e8c.png)

## Content 
Item Name: {{ Item Name }} 
Item Count: {{ Number of selected item }} 
Text: Total 
Price; {{ Total Order Price }} 

## Text Style 
Item Name: 
```
/* Mobile Caption */

font-family: Open Sans;
font-style: normal;
font-weight: normal;
font-size: 12px;
line-height: 16px;
```

Item Count, Total, Price: 
```
/* Mobile Body */

font-family: Open Sans;
font-style: normal;
font-weight: normal;
font-size: 16px;
line-height: 22px;
```

## Color 
Divider: On Surface, Divider (#FFFFFF, 12%) 
Divider (Above Total): On Surface, High Emphasis (FFFFFF, 84%) 
Item name, Item count, Price, Total: On Surface, High Emphasis (#FFFFFF, 84%) 

# Text Button
![image](https://user-images.githubusercontent.com/5694308/81806266-69976400-9546-11ea-859b-9d011d7c0c64.png)

## Content 
Text Button: Delivery Complete (Marks order as completed, removes from "in progress" page)

## Text Style 
Text button: 
```
/* Mobile Color Label */

font-family: Open Sans;
font-style: normal;
font-weight: 600;
font-size: 14px;
line-height: 19px;
text-transform: uppercase;
```

## Color 
Button Text: Secondary (#0E9EC2)

**Comment by bamboochow** [comment]
@abdullahcalisir12 I am setting up our next milestone for this project, what is the status for this issue?

**Comment by abdullahcalisir12** [comment]
ui completed, needs backend support to fetch real data. @bamboochow
