### ISSUE TITLE
Tenant Site - Upcoming Orders

### ISSUE THREAD

**Issue by paigefreeman271** [whynotearth/foodouken.com#193]
# Design File
The specs for page can be found in the [Figma design file](https://www.figma.com/file/Q671pbdFk3omco20xmxk5o/foodouken.com?node-id=2887%3A1)

For the design and the flow, go to the "Tentant CMS" page

# Upcoming Orders
 
Your mission, should you choose to accept 
This page is a list of upcoming orders awaiting delivery for today, and all upcoming orders scheduled for future dates 

- [ ] 1. [Top Nav](#top-nav) 
- [ ] 2. [Tabs](#tabs) 
- [ ] 3. [Product Tickets](#product-tickets) 
- [ ] 4. [Bottom Nav](#bottom-nav)

![image](https://user-images.githubusercontent.com/63047208/81787629-88d4c800-952b-11ea-8e96-03cb35a15a91.png)

<h1 id="top-nav">1. Top Navigation</h1> 

![image](https://user-images.githubusercontent.com/63047208/81790220-490fdf80-952f-11ea-8626-2687c21d5eea.png)

Top navigation is sticky to view top nav viewing window

## Content 
Title: Upcoming Orders
Back button: (Leads to temporary dashboard to #182  )

This component is here:
https://github.com/whynotearth/foodouken.com/blob/staging/src/components/BaseAppBarHeader.vue

<h1 id="Tabs-">2. Tabs</h1> 

![image](https://user-images.githubusercontent.com/63047208/81788702-21b81300-952d-11ea-9bfc-dcaa84c3358e.png)

## Content 
Tab 1 Text : Today (Displays all upcoming orders in the page for today ) 
Tab 2 Text : Upcoming (Displays all upcoming order for future dates ) 

## Text Style
Tab Text 1&2: 
```
/* Mobile Color Label */

font-family: Open Sans;
font-style: normal;
font-weight: 600;
font-size: 14px;
line-height: 19px;
display: flex;
align-items: center;
text-align: center;
text-transform: uppercase;
```

## Color 
Tab 1 Title: On background, high emphasis (#FFFFFF, 100%)
Tab 2 Title: On background, medium Emphasis (#FFFFFF, 54%) 
Tab Background color: Primary (#437784) 
Indictor Line: Secondary color (#0E9EC2, 100%)

## Shadow
```
/* 4 dp */

background: #C4C4C4;
box-shadow: 0px 1px 10px rgba(0, 0, 0, 0.2), 0px 4px 5px rgba(0, 0, 0, 0.12), 0px 2px 4px rgba(0, 0, 0, 0.14);
```

<h1 id="Product-Tickets-">3. Product Ticket</h1> 

![image](https://user-images.githubusercontent.com/63047208/81789943-e6b6df00-952e-11ea-8cf4-34336bb5a677.png)

_**Please refer to the linked issue for product tickets:**_
https://github.com/whynotearth/foodouken.com/issues/171?fbclid=IwAR3BuzfDT-w5XKKrBHmgaRFZvbRnvvMViKXWjwbqVzEFL2ydd6gaGtG1xIQ

<h1 id="Bottom-Nav-">4. Bottom Nav</h1> 

![image](https://user-images.githubusercontent.com/63047208/81790370-81172280-952f-11ea-9230-76ef866454bf.png)
Bottom navigation is sticky to bottom viewing window

_**Please refer to the linked issue for bottom nav:**_
https://github.com/whynotearth/foodouken.com/issues/191

**Comment by bamboochow** [comment]
@abdullahcalisir12 I am setting up our next milestone for this project, what is the status for this issue?
