### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by paigefreeman271** [whynotearth/foodouken.com#196]
# Design File
The specs for page can be found in the [Figma design file](https://www.figma.com/file/Q671pbdFk3omco20xmxk5o/foodouken.com?node-id=2887%3A1)

For the design and the flow, go to the "Tentant CMS" page

# Order Details
 
Your mission, should you choose to accept 

- [ ] 1. [Top Nav](#top-nav) 
- [ ] 2. [Profile&Stats](#profile-stats)
- [ ] 3. [Upcoming](#upcoming) 
- [ ] 4. [In Progress](#in-progress)

![image](https://user-images.githubusercontent.com/14948326/89754302-93d8cd80-db05-11ea-9579-fc628e8f48d4.png)

<h1 id="top-nav">1. Top Navigation</h1> 

![image](https://user-images.githubusercontent.com/14948326/89754332-ac48e800-db05-11ea-9fa7-7a0b8cfd7dd3.png)

## Content 

Title: Foodouken 
Settings Button: {Leads to settings page #147 }

## Text Style 
TItle: 
```
/* Mobile H2 */

font-family: Open Sans;
font-style: normal;
font-weight: bold;
font-size: 24px;
line-height: 33px;
display: flex;
align-items: center;
```

## Asset
![setting](https://user-images.githubusercontent.com/5694308/81808447-eb3cc100-9549-11ea-87ef-13b1e08f1c64.png)

## Color 
Title: On Primary, High Emphasis (#FFFFFF, 84%)
Top Nav Background: Primary (#437784, 100%) 
Settings Icon: On Background, High Emphasis (#FFFFFF, 100%)

## Shadow
Top Navigation Background:
```
box-shadow: 0px 1px 10px rgba(0, 0, 0, 0.2), 0px 4px 5px rgba(0, 0, 0, 0.12), 0px 2px 4px rgba(0, 0, 0, 0.14);
```

<h1 id="profile-stats">2. Profile & Stats</h1> 

![image](https://user-images.githubusercontent.com/14948326/89754449-1e213180-db06-11ea-8009-97462f3e93f9.png)

## Content
Restaurant Avatar: {{ tenant logo from api }}
Title: {{ Restaurant Name }}
URL: {{ Restaurant Foodouken URL }}

{{Page stats will be able to toogle across the screen}}

Stat 1: {{ Number of orders for the day }}
Stat Label 1: ORDERS TODAY
Stat 2: {{ Total Price of all orders for the day }}
Stat Label 2: ORDERED TODAY
Stat 3: {{ Number of page views for the day  }}
Stat Label 3: PAGE VIEWS
Stat 4: {{ Sales Year to day }}
Stat Label 4 SALES YTD
Stat 5: {{  Average order price }}
Stat Label 5: ORDER AVERAGE
Stat 6: {{ Number of regular monthly customers }}
Stat Label 6: REGULARS

## Text Style

Title: 
```
/* Mobile H2 */

font-family: Open Sans;
font-style: normal;
font-weight: bold;
font-size: 24px;
line-height: 33px;
/* identical to box height */

display: flex;
align-items: center;
text-align: center;
```

URL:
```
/* Mobile Caption */

font-family: Open Sans;
font-style: normal;
font-weight: normal;
font-size: 12px;
line-height: 16px;
/* identical to box height */

text-align: center;
```

Stat:
```
/* Mobile H2 */

font-family: Open Sans;
font-style: normal;
font-weight: bold;
font-size: 24px;
line-height: 33px;
display: flex;
align-items: center;
text-align: center;
```
Stat Label:
```
/* Mobile Caption */

font-family: Open Sans;
font-style: normal;
font-weight: normal;
font-size: 12px;
line-height: 16px;
display: flex;
align-items: center;
text-align: center;
```

## Color
Title: On Background, High Emphasis (#FFFFFF, 100%)
URL: On Background, Medium Emphasis (#FFFFFF, 54%)
Stat: Secondary (#0E9EC2, 100%)
Stat Label: On Background, Medium Emphasis (#FFFFFF, 54%)

<h1 id="Upcoming">3. Upcoming</h1> 

![image](https://user-images.githubusercontent.com/14948326/89754432-0fd31580-db06-11ea-94b6-8bd425fd0f13.png)

## Content
Title: Upcoming
Expansion: View all upcoming orders (Leads to #193 Upcoming Orders ) 
Product Ticket Component: 
_**Please see component in link below:**_
https://github.com/whynotearth/foodouken.com/issues/171

## Text Style
Title:
```
/* Mobile H2 */

font-family: Open Sans;
font-style: normal;
font-weight: bold;
font-size: 24px;
line-height: 33px;
display: flex;
align-items: center;
```
Expansion: 
```
/* Mobile Body */

font-family: Open Sans;
font-style: normal;
font-weight: normal;
font-size: 16px;
line-height: 22px;
display: flex;
align-items: center;
```

# Color 
Title: Secondary (#0E9EC2, 100%)
Expansion: On Background, high emphasis (#FFFFFF, 84%)

<h1 id="In Progress">4. In Progress</h1> 

![image](https://user-images.githubusercontent.com/14948326/89754384-dbf7f000-db05-11ea-9a32-684fb0ebe446.png)

## Content

Title: In Progress
Expansion: View all orders in progress (Leads to #194 In Progress) 

Delivery Ticket Component: 
_**Please see Delivery Ticket component in link below:**_
https://github.com/whynotearth/foodouken.com/issues/179

## Text Style
Title:
```
/* Mobile H2 */

font-family: Open Sans;
font-style: normal;
font-weight: bold;
font-size: 24px;
line-height: 33px;
display: flex;
align-items: center;
```
Expansion: 
```
/* Mobile Body */

font-family: Open Sans;
font-style: normal;
font-weight: normal;
font-size: 16px;
line-height: 22px;
display: flex;
align-items: center;
```

# Color 
Title: Secondary (#0E9EC2, 100%)
Expansion: On secondary, high emphasis (#FFFFFF, 84%)

**Comment by bamboochow** [comment]
@abdullahcalisir12 I am setting up our next milestone for this project, what is the status for this issue?

**Comment by abdullahcalisir12** [comment]
ui completed, needs backend support to fetch real data.

**Comment by bamboochow** [comment]
We have updated our routing for this page 
Our top nav, instead of having a "settings icon" leading to settings page, will now have a user account avatar, that leads users to "My Account" page (https://staging.foodouken.com/settings/account)
![image](https://user-images.githubusercontent.com/14948326/87499103-928dbf80-c683-11ea-8dce-70a80a85643e.png)
