### ISSUE TITLE
Terms and Conditions Snack Bar

### ISSUE THREAD

**Issue by paigefreeman271** [whynotearth/foodouken.com#201]
# Design File
The specs for page can be found in the [Figma design file](https://www.figma.com/file/Q671pbdFk3omco20xmxk5o/foodouken.com?node-id=2887%3A1)

For the design and the flow, go to the "Customer View" page

## Terms and Conditions Snack Bar

![image](https://user-images.githubusercontent.com/63047208/82293306-903a1c80-99d6-11ea-8379-a640cd6e8164.png)

![image](https://user-images.githubusercontent.com/63047208/82293443-bf508e00-99d6-11ea-86ec-d4401060da20.png)

For this component, the bar will appear on the welcome screen. The user must pick to agree or the snack bar will follow the user to the next page. 

## Content 

Text: Gotta agree to the terms and conditions {{terms and conditions is a hyperlink that leads to the terms and conditions page}}

Button Text: AGREE {{When the user clicks on this button the snack bar will disappear}}.

## Text Style 

Text: 
```
/* Mobile Caption */

font-family: Open Sans;
font-style: normal;
font-weight: normal;
font-size: 12px;
line-height: 16px;
display: flex;
align-items: center;
```

Button: 
```
/* BUTTON */

font-family: Roboto;
font-style: normal;
font-weight: 500;
font-size: 14px;
line-height: 16px;
/* or 114% */

display: flex;
align-items: center;
text-align: right;
letter-spacing: 0.02em;
text-transform: uppercase;
```
## Color 

Title Text: On Surface, High Emphasis (#FFFFFF, 95%)
Button Text: Secondary (#0E9EC2, 100%)
Background: Primary (#437784, 100%)

**Comment by BurgundyIsAPublicEnemy** [comment]
Currently working on this.

**Comment by paulchrisluke** [comment]
@BurgundyIsAPublicEnemy  https://docs.google.com/document/d/1a_SPIo3jVrYRLzOXgdqxDVZhw0MmfTfvWjzrLipPvkQ/edit?usp=sharing

**Comment by paulchrisluke** [comment]
this is needed for itunes acceptance: https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy

**Comment by paulchrisluke** [comment]
live page for privacy policy https://hub.paulchrisluke.com/-temporary-slug-7a760197-2d5d-4314-876c-ade5923d6dd8

**Comment by paulchrisluke** [comment]
@giteshk11 I think we need an official url on our domain for app store submission. Is it possible to make that route? https://foodouken.com/privacy-policy

**Comment by giteshk11** [comment]
we can do that @paulchrisluke
