### ISSUE TITLE
Staging.foodouken.com Bugs

### ISSUE THREAD

**Issue by bamboochow** [whynotearth/foodouken.com#250]
- [ ] After OAuth, the Link Account (https://staging.foodouken.com/auth/sign-up/link-account) page needs to automatically progress to the next step
![image](https://user-images.githubusercontent.com/14948326/85922001-71b72300-b8aa-11ea-9af2-d748a13f2a42.png)

- [x] When signing up as a new tenant, I am able to skip step 1 entirely by using url (https://staging.foodouken.com/auth/sign-up/link-account) for step 2 directly. This also allows me to progress to step 5 normally with no business information, although pressing "Finish" doesn't let me create a tenant. It also doesn't tell me why I can't create the tenant. 
![image](https://user-images.githubusercontent.com/14948326/85922026-990df000-b8aa-11ea-9014-3c6686a4ac84.png)

- [x] Time selector does not scroll on drag, and there is no indicator (icon?) that clicking above or below changes the number 
https://staging.foodouken.com/auth/sign-up/business-hours
![image](https://user-images.githubusercontent.com/14948326/85922067-d3778d00-b8aa-11ea-9921-c9a33015b624.png)

- [ ] For all price related input, the letter "e" is an allowed character, although it is not registered as a real price. 
https://staging.foodouken.com/tenant/ucha-33/menu/categories/52/items/add
![image](https://user-images.githubusercontent.com/14948326/85922176-75977500-b8ab-11ea-8868-909cd59d13b7.png)

- [ ] When creating a product incorrectly (leaving out price, adding blank variation), there is an error message "One of more validation error occured." Users need to know what the errors are. 
https://staging.foodouken.com/tenant/ucha-33/menu/categories/52/items/add
![unknown](https://user-images.githubusercontent.com/14948326/85922247-230a8880-b8ac-11ea-874f-72d11d99c830.png)

- [x] "Sell Out" option in menu only leads to "edit item" and does not actually label item as "sold out" 
https://staging.foodouken.com/tenant/ucha-33/menu/categories/52/items
![image](https://user-images.githubusercontent.com/14948326/85922307-81376b80-b8ac-11ea-9ae0-df04a22e3e8b.png)
- [x] Category is not displayed dynamically 
https://staging.foodouken.com/tenant/ucha-33/menu/categories/52/items
![image](https://user-images.githubusercontent.com/14948326/85922296-67962400-b8ac-11ea-975a-c6bd97617149.png)

- [ ] I am able to access https://staging.foodouken.com/tenant/atharva-sharma-30/menu/categories just from url (logged in or not). I am able to continue to "add new categories" and fill out the form, but I'm not actually allowed to save a new category. Only logged in tenant should have access to the "category/item" tenant pages SPECIFICALLY for their own associated account. 

- [x] Item/Cart from one tenant persists in different tenant's customer view, and I am able to  have a cart with multiple tenant's items. Cart should be cleared when moving between tenants.
https://staging.foodouken.com/shop/ucha-33
![unknown (1)](https://user-images.githubusercontent.com/14948326/85922476-ca3bef80-b8ad-11ea-9b5a-7fcaa8cf1242.png)
![unknown (2)](https://user-images.githubusercontent.com/14948326/85922478-cc05b300-b8ad-11ea-81e9-1e41d737f6ea.png)

- [x] Cannot decrease amount of items, or remove items in my cart. Can only add more. 
https://staging.foodouken.com/shop/ucha-33
![unknown (3)](https://user-images.githubusercontent.com/14948326/85922498-f9eaf780-b8ad-11ea-8a22-7e8c1d74adbd.png)

- [ ] There's no actual method of telling whether you're actually logged in or not, or what account you're logged into, just whether or not you can ultimately "submit" an action and get a success page.

- [x] If image not uploaded for product in https://staging.foodouken.com/tenant/ucha-33/menu/categories/52/items/add then show tenant logo instead of this image error 
![unknown (2)](https://user-images.githubusercontent.com/14948326/85922562-96ad9500-b8ae-11ea-8d71-2761b2a38061.png)

**Comment by atharva3010** [comment]
Decimal support added for price inputs.

**Comment by paulchrisluke** [comment]
After OAuth, the Link Account (https://staging.foodouken.com/auth/sign-up/link-account) page needs to automatically progress to the next step 

Assigned to @abdullahcalisir12 and made single issue here: https://github.com/whynotearth/foodouken.com/issues/257

 I am able to access https://staging.foodouken.com/tenant/atharva-sharma-30/menu/categories just from url (logged in or not). I am able to continue to "add new categories" and fill out the form, but I'm not actually allowed to save a new category. Only logged in tenant should have access to the "category/item" tenant pages SPECIFICALLY for their own associated account.

Assigned to @atharva3010 and made a single issue here:  https://github.com/whynotearth/foodouken.com/issues/258

the above issue covers this item as well: There's no actual method of telling whether you're actually logged in or not, or what account you're logged into, just whether or not you can ultimately "submit" an action and get a success page.

**Comment by paulchrisluke** [comment]
I split the rest of these bugs inot inidivudal issues for better tracking, clsoing
