### ISSUE TITLE
Foodouken Order Confirmation Email

### ISSUE THREAD

**Issue by bamboochow** [whynotearth/foodouken.com#252]
# Design File
For design reference, please see files in [Figma](https://www.figma.com/file/Q671pbdFk3omco20xmxk5o/foodouken.com?node-id=1245%3A57965)

You can find the designs for this issue in the "Email Design" Page of Figma 

Our current HTML is here:
```
<html lang="en">

<body style="font-family: sans-serif; color: #191C21;">
    <h1>What's coming</h1>
    <div>
        <p>{{orderProducts}}</p>
    </div>
   

    <div><small>Sub-total ${{subTotal}}</small></div>
    <div><small>Tax ${{tax}}</small></div>
    <div><small>Delivery Fee ${{deliveryFee}}</small></div>
    <hr />

    <h2>Total - ${{amount}}</h2>
     <hr />
    <h3>Customer Details</h3>
    <div>
        <p>Delivery Address: {{deliveryAddress}}</p>
        <p>Customer name: {{name}}</p>
        <p>Phone Number: {{phone}}</p>
        <p>Email: {{email}}</p>
        <p>Payment Method: {{paymentMethod}}</p>
        <p>Estimated Delivery Time: {{deliveryTime}}</p>
    </div>

    {{#if message}}
        <h3>Special Requests</h3>
        <p>{{message}}</p>
    {{/if}}

    <hr />

    <h2>Thank You!</h2>
    <p>
        Thank you for ordering! Your food is being prepared. Please be prepared to pay ${{amount}} upon arrival.
    </p>

    <h2>{{tenant.h2}}</h2>
    <p>{{tenant.h2}}</p>
    <p><a href="{{googleMaps}}">{{googleMaps}}</a></p>
    <p><a href="{{tenant.phone}}">+{{tenant.phone}}</a></p>
    <p><a href="{{tenant.email}}">{{tenant.email}}</a></p>
</body>

</html>
```

This html needs to be styled below. You can use https://mjml.io/ as a framework for this or do raw html/css.

# Order Confirmation Email 
- [ ] Header
- [ ] Order Details 
- [ ] Customer Details 
- [ ] Tenant Info
![image](https://user-images.githubusercontent.com/14948326/85923666-396a1180-b8b7-11ea-8996-60b7896cfd27.png)

# Header 
![image](https://user-images.githubusercontent.com/14948326/85923670-40911f80-b8b7-11ea-9259-dc167a69824d.png)

## Content 
Avatar: {Foodouken Logo} 
H1 Title: Thanks For Your Order!

# Order Details 
![image](https://user-images.githubusercontent.com/14948326/85923542-02dfc700-b8b6-11ea-9e41-d1e5c85a2451.png)

## Content
H3 Title: What's Coming 
This is customer's cart displayed 
{ Ordered items, price, and quantity }
{Subtotal, Delivery Fees, Tax} 
{Total}

# Customer Details 
![image](https://user-images.githubusercontent.com/14948326/85923587-7f72a580-b8b6-11ea-9d97-0d562d78f8ab.png)

## Content 
H3 Title: Customer Details 
Item 1: Delivery Address { add Google Maps link OR address }
Item 2: Customer Name { Customer Name } 
Item 3: Phone Number { Phone Number } 
Item 4: Email {Customer Email }
Item 5: Payment Method { Selected Payment Method } 
Item 6: Estimated Delivery { Date and Time of estimated delivery } 

# Tenant Info 
![image](https://user-images.githubusercontent.com/14948326/85923651-10e21780-b8b7-11ea-8b76-7c17a7a5e5c4.png)

## Content 
H3 Title: { Tenant Name } 
Item 1: { Tenant Address } 
Item 2: { Tenant Phone Number } 
Item 3: { Tenant Email } 

# Text Styles 
H1 Titles: 
```
/* Desktop H1 */

font-family: Open Sans;
font-style: normal;
font-weight: bold;
font-size: 64px;
line-height: 87px;
```

H3 Titles, Cart Total, Item Title: 
```
/* Desktop H3 */

font-family: Open Sans;
font-style: normal;
font-weight: bold;
font-size: 36px;
line-height: 49px;
/* identical to box height */
```

Item Info: 
```
/* Desktop Body 1 */

font-family: Open Sans;
font-style: normal;
font-weight: normal;
font-size: 32px;
line-height: 44px;
```

Subtotal, Delivery Fees, Tax: 
```
/* Desktop Caption */
font-family: Open Sans;
font-style: normal;
font-weight: normal;
font-size: 24px;
line-height: 33px;
/* identical to box height */
```

**Comment by bamboochow** [comment]
# H1 Title 
"Thanks For Your Order" should be H1 text, much bigger than the other text styles in the email 
```
/* Mobile H1 */

font-family: Open Sans;
font-style: normal;
font-weight: bold;
font-size: 32px;
line-height: 44px;
```

# H3 Titles 
"Customer Details" and the "{Tenant Name}" title of the last sections should be the same font styles (H3) as "What's Coming"
![image](https://user-images.githubusercontent.com/14948326/88059094-942d1b00-cb8e-11ea-99d7-7409c3d25322.png)
![image](https://user-images.githubusercontent.com/14948326/88059078-8a0b1c80-cb8e-11ea-8578-b0a483a1265d.png)
![image](https://user-images.githubusercontent.com/14948326/88059173-ae66f900-cb8e-11ea-8500-0f783e1bfee6.png)

# VAT Percentage 
VAT should display inputted {tax percentage} added onto the bill. 
![image](https://user-images.githubusercontent.com/14948326/88059416-04d43780-cb8f-11ea-9e93-eaccc1268f35.png)

# Desktop Title/Icon misaligned 
In the desktop view of the email (gmail, google chrome) you see a positioning mismatch with the titles and icons 
![image](https://user-images.githubusercontent.com/14948326/88058599-e3268080-cb8d-11ea-9bd6-8a4f8404d3e5.png)

This is not an issue in mobile
![image](https://user-images.githubusercontent.com/14948326/88058734-19fc9680-cb8e-11ea-80b9-02f7a9cccd39.png)

# Content within Margins 
Email content should be within the margins defined by the dividers on the email. It is currently aligned like the image below:
![image](https://user-images.githubusercontent.com/14948326/88059601-49f86980-cb8f-11ea-86da-d5cf1c3d44f5.png)

**Comment by paulchrisluke** [comment]
we are going to shift to sms notifications. closing
