### ISSUE TITLE
"E" is accepted in Price Input

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/foodouken.com#260]
For all price related input, the letter "e" is an allowed character, although it is not registered as a real price. 
https://staging.foodouken.com/tenant/ucha-33/menu/categories/52/items/add

this should not be allowed as an input if this is not an acceptable character. (also having an exponential allowed for price might end up real crazy) 

![image](https://user-images.githubusercontent.com/14948326/85922176-75977500-b8ab-11ea-8868-909cd59d13b7.png)

Part of the discussion in discord included for reference: 
![image](https://user-images.githubusercontent.com/5694308/85979916-98d93600-ba0b-11ea-9e0d-3661969334cc.png)
https://github.com/vuejs-tips/v-money

**Comment by paulchrisluke** [comment]
Is probably related to scientific notation I'll get more details from @mmartinnn later

**Comment by atharva3010** [comment]
This isn't an error as once the user moves away from the input field, `e` gets converted appropriately to a number.
Basically, `2e5` will become 20000
