### ISSUE TITLE
Handle Location Prompt like Tinder

### ISSUE THREAD

**Issue by bamboochow** [whynotearth/foodouken.com#264]
Handle Location Prompt like Tinder for better cross-device support 

https://developers.google.com/web/fundamentals/native-hardware/user-location

excerpt from above documentation:

Set up a timer that triggers after a short period; 5 seconds is a good value.
If you get an error message, show a message to the user.
If you get a positive response, disable the timer and process the results.
If, after the timeout, you haven't gotten a positive response, show a notification to the user.
If the response comes in later and the notification is still present, remove it from the screen.

```
button.onclick = function() {
  var startPos;
  var nudge = document.getElementById("nudge");

  var showNudgeBanner = function() {
    nudge.style.display = "block";
  };

  var hideNudgeBanner = function() {
    nudge.style.display = "none";
  };

  var nudgeTimeoutId = setTimeout(showNudgeBanner, 5000);

  var geoSuccess = function(position) {
    hideNudgeBanner();
    // We have the location, don't display banner
    clearTimeout(nudgeTimeoutId); 

    // Do magic with location
    startPos = position;
    document.getElementById('startLat').innerHTML = startPos.coords.latitude;
    document.getElementById('startLon').innerHTML = startPos.coords.longitude;
  };
  var geoError = function(error) {
    switch(error.code) {
      case error.TIMEOUT:
        // The user didn't accept the callout
        showNudgeBanner();
        break;
    }
  };

  navigator.geolocation.getCurrentPosition(geoSuccess, geoError);
};
```

# Prompt 
![image](https://user-images.githubusercontent.com/14948326/86356722-e9b08f00-bc96-11ea-8024-9674aff12787.png)

# Content 
Text: Foodouken uses your location to get your favorite dishes straight to you. 
Button 1: Cancel 
Button 2: Allow 

# Color 
Text: On Surface, Medium Emphasis
Button 1: On Surface, Medium 
Button 2 Background: Secondary (#0E9EC2)
Button 2 Text: On Secondary, High Emphasis (#FFFFFF, 84%) 
Card: 
```
/* 24 dp */

background: #C4C4C4;
box-shadow: 0px 11px 15px rgba(0, 0, 0, 0.2), 0px 9px 46px rgba(0, 0, 0, 0.12), 0px 24px 38px rgba(0, 0, 0, 0.14);
```

# Text Styles 
Text: 
```
/* Mobile Body */

font-family: Open Sans;
font-style: normal;
font-weight: normal;
font-size: 16px;
line-height: 22px;
/* identical to box height */
```

Text Button, Button: 
```
/* Mobile Color Label */

font-family: Open Sans;
font-style: normal;
font-weight: 600;
font-size: 14px;
line-height: 19px;
/* identical to box height */

text-transform: uppercase;
``` 

# Shadow
Card: 
```
/* Surface DM 24 dp */

background: linear-gradient(0deg, rgba(255, 255, 255, 0.16), rgba(255, 255, 255, 0.16)), #003037;
```

**Comment by paulchrisluke** [comment]
@bamboochow we need to design the popup prompt for this, then prototype and provide to front end team

**Comment by paulchrisluke** [comment]
![Screenshot_20200702-210601](https://user-images.githubusercontent.com/5694308/86386698-55f1b980-bcbc-11ea-821c-1de3abc212c3.png)
![Screenshot_20200702-210606](https://user-images.githubusercontent.com/5694308/86386708-58ecaa00-bcbc-11ea-864e-c520ff5bcf92.png)
@abdullahcalisir12 

You can replicate this behavior on tinder by loading it on Firefox incognito
