### ISSUE TITLE
ping endpoint returns loginProviders as an empty array

### ISSUE THREAD

**Issue by abdullahcalisir12** [whynotearth/foodouken.com#265]
Ping returns empty loginProviders array that's why I can't use logout function to give ability to user to logout.

![image](https://user-images.githubusercontent.com/29024217/86042693-35bdc280-ba50-11ea-9f87-bf389a1212df.png)

![image](https://user-images.githubusercontent.com/29024217/86042706-3b1b0d00-ba50-11ea-9500-0ffe458974e2.png)

**Comment by ctyar** [comment]
@abdullahcalisir12 I checked your mentioned account and it seems you have not connected your Google/Facebook
And that's why LoginProviders is empty
Can you please check with your other account `***@gmail.com` and confirm that it works

**Comment by abdullahcalisir12** [comment]
@ctyar description updated.
