### ISSUE TITLE
Tenants unable to submit orders as customers

### ISSUE THREAD

**Issue by bamboochow** [whynotearth/foodouken.com#268]
Users with emails registered as a tenant are not able to submit a delivery order as a customer. 
All emails associated with registered tenants are displayed as "user name {email} is already taken" 

This was tested after creating a tenant from a new email and testing the email through our checkout process. 
Tenant: https://staging.foodouken.com/auth/sign-up/success/test-tenant-100-40
![image](https://user-images.githubusercontent.com/14948326/86042056-ce643a80-ba70-11ea-8c0e-74630bec4be5.png)

**Comment by joeelia** [comment]
@ctyar How is this a front-end issue if the '**User name 'chrischarging@gmail.com' is already taken.** is coming from an API call. This has to be a server issues.

**Comment by ctyar** [comment]
The user already registered with this email address so we should just direct them to a login page and continue the order process from there

**Comment by joeelia** [comment]
Oh alright that makes sense. I’ll look into making a PR tomorrow
