### ISSUE TITLE
Fields for tags, taxRate, deliveryFee and deliveryTime on CMS

### ISSUE THREAD

**Issue by atharva3010** [whynotearth/foodouken.com#279]
Right now, the CMS doesn't allow the user to save deliveryFee and deliveryTime. As a result, by default the deliveryFee is 0 and on the frontend we have a static 45 min delivery time

**Comment by atharva3010** [comment]
We also need to add fields for an array “tags” and number taxRate

**Comment by paulchrisluke** [comment]
@bamboochow we should design this

**Comment by bamboochow** [comment]
Closing issue, will create new issues for separate features
