### ISSUE TITLE
Log In Entry Point

### ISSUE THREAD

**Issue by bamboochow** [whynotearth/foodouken.com#283]
We are adding a Log In/Account button to allow users account access while  they are in the Foodouken home page or store pages

# Logging In 
We are adding a text button 
This button exists on HOME PAGE https://foodouken.com/ and STORE PAGES https://foodouken.com/shop/angkor-tacos-1

**Text Button**
Content: Log In (leads to https://foodouken.com/auth/login
Color: Secondary (#0E9EC2)
Text Style: 
```
/* Mobile Color Label */

font-family: Open Sans;
font-style: normal;
font-weight: 600;
font-size: 14px;
line-height: 19px;
/* identical to box height */

text-transform: uppercase;
```

![image](https://user-images.githubusercontent.com/14948326/86344755-dc8aa480-bc84-11ea-853d-1261ee087eea.png)

 # After Log IN 
The "log in" text button is switched out with a avatar

**Avatar**
Content: { Placeholder image, Gmail Icon, or FB profile picture } (leads to My Accounts https://staging.foodouken.com/settings/account page) 

![image](https://user-images.githubusercontent.com/14948326/86345720-1ad49380-bc86-11ea-8bac-1c9bd017f959.png)

_____

We also need to add the login button a last step before checkout here:

![image](https://user-images.githubusercontent.com/5694308/87496210-55263380-c67d-11ea-8710-23f748948378.png)

**Comment by paulchrisluke** [comment]
@joeelia do you have suggestions on how to unify our login flow? If they log in here I assume we could save their info for next time? persist the logged in state?
