### ISSUE TITLE
Open Shared Link in New Browser Window

### ISSUE THREAD

**Issue by bamboochow** [whynotearth/foodouken.com#303]
Currently, when the link is shared on messenger, it opens in webview, which cannot access our features. 
We need the site to be opened on a separate new browser window, using the phones default browser. 

![received_583669165668638](https://user-images.githubusercontent.com/14948326/86705145-c6dbfd00-c03f-11ea-9497-97069021fe7b.jpeg)

**Comment by joeelia** [comment]
This is impossible to do with code. Its a native feature in Facebook Messenger..
