### ISSUE TITLE
Change "Payment Methods" Sign Up Step to include Fees

### ISSUE THREAD

**Issue by bamboochow** [whynotearth/foodouken.com#321]
# Design File
The specs for page can be found in the [Figma design file](https://www.figma.com/file/Q671pbdFk3omco20xmxk5o/foodouken.com?node-id=2887%3A1)

For the design and the flow, go to the "Tentant CMS" page

# Order Options 

The payment methods page will be updated to include taxes and delivery fees, as well as renamed to "order options" 

![image](https://user-images.githubusercontent.com/14948326/87123608-4f150900-c2b1-11ea-8ca4-9b14518d9882.png)

USE THIS CODE: 
"Payment Method" Sign UP Page: https://github.com/whynotearth/foodouken.com/blob/staging/src/components/forms/PaymentMethod.vue

Sign Up: https://github.com/whynotearth/foodouken.com/blob/staging/src/components/auth/SignUpForm.vue

# Content 
Text 1: `Set your taxes and delivery fees:`
Text Field 1: Tax Rate (Accept percentage, show when customers order from tenant as a sub fee)
Text Field 2: Delivery Fee (Accept dollar amount, show when customers order from tenant as a delivery fee) 

Text 2: `Select the payment methods that you accept:` 
Checkbox 1: Cash

**Comment by joeelia** [comment]
@bamboochow does Meredith-Core accept **tax rate** and **delivery fee** fields to the signup api? Specially to the **/companies/{{ company-slug }}/tenants** endpoint. I'm guessing that the endpoint does not accept those values so a feature enchantment would have to be requested for Meredith-Core to add those fields to add **tax rate** and **delivery fee** on the end-point / database.

Also, this is a rather complex request for the front-end. So I don't think ill be able to tackle it

**Comment by paulchrisluke** [comment]
this should be a backend first, get ourselves an endpoint for it and then move to front end

**Comment by bamboochow** [comment]
# Display 
Tax rate and delivery fee should show up on customer cart like so, and applied to total price of customer's cart. 

![image](https://user-images.githubusercontent.com/14948326/87290437-34989500-c528-11ea-99bb-b22e4184af99.png)

## Content 
VAT ({tax percentage}%)       {tax amount}
Delivery Fee                          {delivery fee amount}

**Comment by bamboochow** [comment]
backend issue added https://github.com/whynotearth/foodouken.com/issues/329 , this is a frontend issue
