### ISSUE TITLE
Promotions 

### ISSUE THREAD

**Issue by bamboochow** [whynotearth/foodouken.com#332]
# Design File
The specs for page can be found in the [Figma design file](https://www.figma.com/file/Q671pbdFk3omco20xmxk5o/foodouken.com?node-id=2887%3A1)

For the design and the flow, go to the "Tentant CMS" page

# Related Code 
Top Navigation: https://github.com/whynotearth/foodouken.com/blob/staging/src/components/BaseAppBarHeader.vue
Toggle: https://github.com/whynotearth/foodouken.com/blob/staging/src/components/inputs/BaseToggleSwitch.vue
Product Card: https://github.com/whynotearth/foodouken.com/blob/staging/src/components/cards/ProductCard.vue

# Promotions Page
This is a promotions page that applies a discount to all products store wide. Users will access this page through an option in the "settings" page. 
![image](https://user-images.githubusercontent.com/14948326/87403203-c4047d80-c5e6-11ea-8b04-01aaf0b70285.png)

# Content 
Top Nav: Promotion 
Back: (Leads to Settings page)
Text: Promotion will be applied store-wide.
Text Field Label: Discount (This is the discount percentage that will be applied to all products in the tenant's store)
Input Label: %
Toggle: Activate/inactivate promotion (On press, apply discount to store. inactivating toggle will remove discounts from store)

# Text Style 
Top Navigation: 
```
/* Mobile H2 */

font-family: Open Sans;
font-style: normal;
font-weight: bold;
font-size: 24px;
line-height: 33px;
```

Body: 
```
/* Mobile Body */

font-family: Open Sans;
font-style: normal;
font-weight: normal;
font-size: 16px;
line-height: 22px;
```
Floating Label: 
```
/* Mobile Caption */

font-family: Open Sans;
font-style: normal;
font-weight: normal;
font-size: 12px;
line-height: 16px;
```

Input/Input Label: 
```
/* Mobile Body */

font-family: Open Sans;
font-style: normal;
font-weight: normal;
font-size: 16px;
line-height: 22px;
```

# Colors 
Top Navigation Background: Primary (#437784)
Top Nav text: On Primary, High (#FFFFFF, 84%)
Text: On Backgorund, Medium (#FFFFFF, 54%) 
Input Text: On Surface, High (#FFFFFF, 84%)
Text Field Label: On Surface, Medium(#FFFFFF, 54%) 
Floating Label: On Surface, Medium(#FFFFFF, 54%) 
Inactive Toggle Knob: Primary (#437784)
Inactive Toggle Track: Divider (#FFFFFF, 12%)
Active Toggle Knob: Secondary (#0E9EC2)
Active Toggle Track: Secondary, Medium (#0E9EC2, 54%)
Card: 
```
/* Surface DM 1 dp */

background: linear-gradient(0deg, rgba(255, 255, 255, 0.05), rgba(255, 255, 255, 0.05)), #003037;
```

# Shadow
Card: 
```
/* 1 dp */

background: #C4C4C4;
box-shadow: 0px 1px 3px rgba(0, 0, 0, 0.2), 0px 2px 2px rgba(0, 0, 0, 0.12), 0px 0px 2px rgba(0, 0, 0, 0.14);
```

# Behavior 
Users can add a percentage and activate the toggle to start the promotion. Once started, all items in the shop would appear with this tag on their store item, as well as updated pricing: 
![image](https://user-images.githubusercontent.com/14948326/87379188-e0d68c00-c5b9-11ea-9bed-23499238d1af.png)

Once a user decides to end their promotion, they can press the toggle to end the promotion. 

### Promotion Tag: 
**Content** 
Tag Content: {percentage} OFF!

**Color** 
Tag Background: Secondary (#0E9EC2)
Tag Text: On Secondary, High (#FFFFFF, 84%) 
Original Price: On Surface, disabled (#FFFFFF, 38%) 
Promotion Price: On Surface, Medium Emphasis (#FFFFFF, 54%) 

**Text** 
Tag Text: 
```
/* Mobile Color Label */

font-family: Open Sans;
font-style: normal;
font-weight: 600;
font-size: 14px;
line-height: 19px;
text-transform: uppercase;
```

![image](https://user-images.githubusercontent.com/14948326/87404603-8d2f6700-c5e8-11ea-8c83-f077bb521daa.png)

**Comment by paulchrisluke** [comment]
backend ready: /api/v0/companies/{companySlug}/tenants/{tenantSlug}
