### ISSUE TITLE
Replace Logo image Everywhere

### ISSUE THREAD

**Issue by bamboochow** [whynotearth/foodouken.com#353]
# Replace Logo image with New Foodouken Logo 
The foodouken site currently has this image as its logo everywhere
https://res.cloudinary.com/whynotearth/image/upload/v1587687189/foodouken/foodouken_logo_uq4iev_abk1wn.png
![image](https://res.cloudinary.com/whynotearth/image/upload/v1587687189/foodouken/foodouken_logo_uq4iev_abk1wn.png)

We need to replace the foodouken logo everywhere with this new logo: 
https://res.cloudinary.com/whynotearth/image/upload/v1595338514/foodouken/Foodouken_Blobby_2_dyvaw5.png

This is a transparent white PNG and should have the background color behind it 
![image](https://res.cloudinary.com/whynotearth/image/upload/v1595338514/foodouken/Foodouken_Blobby_2_dyvaw5.png 
)

This includes: 

- Success Modal logo
- Default item/category image
- loading pages logo
- Order confirmations logo
etc

**Comment by paulchrisluke** [comment]
done I think
