### ISSUE TITLE
Promotion discount changes product base price when editing products

### ISSUE THREAD

**Issue by bamboochow** [whynotearth/foodouken.com#359]
# Issue
When editing a product while a promotion is active, the saved product price is not the base item price, but the discounted product price. Upon saving the product (without editing price), a second discount is taken. 

For example: 
1. product's originally set base price is $9, promotion is set to 12% discount 
2. Upon entering the product edit page https://staging.foodouken.com/tenant/paul-chris-luke-47/menu/categories/89/items/53/edit , you can see that product price is saved to $7.92 instead of the expected $9
![image](https://user-images.githubusercontent.com/14948326/88561265-61d16100-d059-11ea-884a-25ab39b93f36.png)

3. Edit any field EXCEPT for price, and SAVE edit 

4. product's price is FURTHER discounted to $6.9696 (12% of $7.92)
![image](https://user-images.githubusercontent.com/14948326/88561460-a3faa280-d059-11ea-9665-e10503b43ba8.png)

HOWEVER, if you edit the price on https://staging.foodouken.com/tenant/paul-chris-luke-47/menu/categories/89/items/53/edit the item, edited price will be saved as your new price and discounted as expected. 

# Expected Behavior
Product's saved BASE PRICE should always remain the same unless actively edited, with the promotional discount applied on top
so, there should be no double application of promotion when editing product info, and saved product price should always remain the same

**Comment by bamboochow** [comment]
@giteshk11 can you take a look at this please?

**Comment by giteshk11** [comment]
@ctyar i think you also need to put a check at your end if its not there i case if the discountPercent > 0 then update the originalPrice not the price because price will have the price after discount is applied.

**Comment by ctyar** [comment]
@giteshk11 Right now the API receives a `price` value (when creating and editing) and returns a `price` and `originalPrice`(when displaying products)
When a product doesn't have any discounts available the `price` and `originalPrice` are equal
But if the shop has a promotion you create a product with `price` = $10
and the API returns you `price` = $8 and `originalPrice` = $10
`price` is the final price the customer has to pay and `originalPrice` is the value before discounts
So in an edit form, you should read the value from `originalPrice` and send it as `price` to the API
One thing I can do to make this a little bit more clear is to rename `price` filed when creating and editing the product to `originalPrice`
