### ISSUE TITLE
unable to create items "please fill out form properly"

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/foodouken.com#370]
https://staging.foodouken.com/tenant/paul-chris-luke-47/menu/categories/95/items/add

chrome desktop
attempting to create item gives "please fill out form properly" even though all fields are filled.

Possibly related to promotions? 

it seems like this field is reqiured
but i dont see an orginalPrice field in the form
that might be casuing the issue

https://github.com/whynotearth/foodouken.com/blob/eae91bb39b2c59c3c8c0b6c9456dda91c7a88a1d/src/views/MenuItemAddEdit.vue#L146

https://github.com/whynotearth/foodouken.com/blame/eae91bb39b2c59c3c8c0b6c9456dda91c7a88a1d/src/views/MenuItemAddEdit.vue#L146

related PR: https://github.com/whynotearth/foodouken.com/issues/359

![image](https://user-images.githubusercontent.com/5694308/90325070-0b44ac00-dfa1-11ea-96ca-f3e3809d1cc9.png)

**Comment by giteshk11** [comment]
@paulchrisluke we can close this
