### ISSUE TITLE
on desktop, placeholder text in input fields should not show once the input is selected

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/foodouken.com#49]
right now the text remains until you start typing:
![image](https://user-images.githubusercontent.com/5694308/78668375-c4fd8300-7904-11ea-968b-94fe4e5aeee7.png)

the text should clear the input field, leaving only the blinking text curser

**Comment by paulchrisluke** [comment]
while in here, need to make the input field also match vueitfy a bit more. round the cornrers on active state, increase stroke https://vuetifyjs.com/en/components/text-fields/

**Comment by GerardBalaoro** [comment]
@paulchrisluke What you're seeing is the default focus styling the browser adds (which does not wrap rounded corners). Totally disabling it would is not ideal. Tailwind actually recommends an alternative.

> Use the `.shadow-outline` utility to apply a focus-ring-style shadow to an element. This can be useful when combined with `.focus:outline-none` to create a better looking focus style that follows an element's border radius.

So the solution would be to add the classes `focus:outline-none focus:shadow-outline` to the input element.

**Comment by GerardBalaoro** [comment]
For the placeholder text. That's because the input has both a placeholder and a label. One solution would be to remove the placeholder altogether and re-style the label so that it is large when the element is empty or not selected.

The other is to use the `::placeholder` pseudo-element (not supported on IE11)

```css
input:focus::placeholder {
  visibility: none;
}
```

**Comment by paulchrisluke** [comment]
beautifully done! Thanks for the contribution :)
