### ISSUE TITLE
hide/remove "empty cart" component on mobile

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/foodouken.com#65]
@sally and @atharva3010 and I were having a discussion about this in discord earlier.

I wonder if it makes the most sense on mobile to 

1. remove the "empty cart" component entirely. It doesn't really add much to the user experience, and prevents them from seeing the store content sooner. 
2. make the "order now" button launch the user directly into the checkout flow... since the empty cart would no longer be populating, there would be nothing to scroll to (which is always annoying). Once the user is in the checkout process, the cart is always present below, and editable, so I think that may be good enough for now?

What do you guys think?

**Comment by sally** [comment]
@paulchrisluke 

1. Hey, this is a good idea - I think we should keep Empty Cart on desktop though. It's a fine placeholder for the cart before the user adds stuff.

2. I think the "Order Now" button is already doing what you're describing and initiating the checkout flow (and not just scrolling the user to the Cart). See [here](https://github.com/whynotearth/foodouken.com/pull/61/files#diff-a3c1ef62355391e980435ca4d7ea595bR77-R80)

**Comment by paulchrisluke** [comment]
yea perfect, keepign cart on desktop is good. I suppose this issue will just be about hiding the cart on mobile then :)

**Comment by sally** [comment]
Renaming this issue to be more accurate of what the task discussed in the comments are

**Comment by paulchrisluke** [comment]
beautiful!
