### ISSUE TITLE
Checkout Process - Customer Info (Mobile)

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/foodouken.com#8]
In this issue we will be making the 1st step of our checkout process for Foodouken, a food delivery app. 

# Customer Info
![image](https://user-images.githubusercontent.com/5694308/78236668-83379b80-7504-11ea-8314-b9474f920906.png)
This is the 1st of 5 steps in the Foodouken checkout process. In this step, customers have already selected their cart and are inputting their information and any special requests for their order. 

This page has various parts: 
1. Top Navigation with Stepper
2. Input Area
3. Divider
4. Cart 
5. Footer 

## 1. Top Navigation with Stepper 
![image](https://user-images.githubusercontent.com/5694308/78236964-eb867d00-7504-11ea-8a54-7547919bd8e2.png)
The top navigation bar shows what step of the checkout process the user is on as well as allow them to move back to the menu page/on to the next step. **This top navigation is the same one as every page in the Checkout Process** 

It has 4 major parts: 
1. Background
2. Page Title
3. Action Icon
4. Progress Dot Stepper

### 1. Background
![image](https://user-images.githubusercontent.com/5694308/78236964-eb867d00-7504-11ea-8a54-7547919bd8e2.png)
The background of the top navigation is 88 pixels in height, full viewing window width.
Color: Primary
Shadow: 4dp

### 2. Page Title 
![image](https://user-images.githubusercontent.com/5694308/78237080-0eb12c80-7505-11ea-8e10-87d127fe9f5c.png)
This page title is 16 pixels from the top of the screen, and 16 pixels from the action icon, and 28 pixels from the Progress dot stepper. 

Color: On Primary
Emphasis: High
Font: H3

### 3. Action Icon
![image](https://user-images.githubusercontent.com/5694308/78237239-40c28e80-7505-11ea-95db-046d4af84791.png)
The 24x24 action icon takes the users back to the menu. 
Color: On Primary
Emphasis: Medium

### 4. Progress Dot Stepper
![image](https://user-images.githubusercontent.com/5694308/78329082-f85dac00-75aa-11ea-894c-a4bab1df5aa6.png)
This stepper shows the progress of our article drafting process. There is a total of 5 pages for this process, and the stepper should be centered and highlighting the 1st dot as this is the 1st step.

Active color: Secondary 
Inactive color: On Primary (Disabled)

## 2. Input Area
![image](https://user-images.githubusercontent.com/5694308/78237647-cc3c1f80-7505-11ea-8a06-565dd59190e3.png)
The input area has 2 sections, One for the personal information, and one for the special requests. These sections are 8 pixels apart, 24 pixels from the top bar and 40 pixels from the button 

The input area has 3 parts: 
1. Background Card 
2. Text Field 
3. Button

### 1. Background Card
![image](https://user-images.githubusercontent.com/5694308/78238138-6dc37100-7506-11ea-917c-8c9a5374b095.png)
The background card distinguishes the different sections. The card extends 24 pixels above and below, and 8 pixels to the left and right of the text fields inside 
Color: 1 dp - Dark Mode Overlay
Shadow: 1 dp

### 2. Text Field
![image](https://user-images.githubusercontent.com/5694308/78325611-50dc7b80-75a2-11ea-91b2-176c42cddcca.png)

This area uses the default [vuetify text outline fields](https://vuetifyjs.com/en/components/text-fields/), which includes these parts: 
1. Label 
2. Border 
3. Input Text
4. Word Limit

**1. Label**
![gif](https://i.gyazo.com/38927836b02bbdff55225d332d6cb32b.gif)
The label text behaves just as the gif above, where it is presented first as within the outline and then floats out to be displayed on the border. 

Label Text: 
Font: Mobile Body 1
Color: On Surface
Emphasis: Disabled 

Floating Text: 
Font: Caption
Color: On Surface
Emphasis: Disabled 

![gif](https://i.gyazo.com/9a17471c5e30f78be6ea3107a9e7a150.gif)
When selected, the Floating text in the field changes colors 
Color: On Surface
Emphasis; High

**2. Border**
![image](https://user-images.githubusercontent.com/5694308/78325853-132c2280-75a3-11ea-946a-87508cc27836.png)
All of our text fields have a width of 312 pixels, centered. 
The height of the field is determined by amount of content it contains. 
Color: On Surface
Emphasis: Disabled 

![gif](https://i.gyazo.com/9a17471c5e30f78be6ea3107a9e7a150.gif)
When selected, we want the border to be highlighted
Color; On Surface
Emphasis: High

**3. Input Text**
![gif](https://i.gyazo.com/4b762ebe7386b86ff7dc4db5fd48816a.gif)
For any text that are typed in, this text is displayed 
Font: Mobile Body 1
Color: On Surface
Emphasis: High

### 3. Button 
![image](https://user-images.githubusercontent.com/5694308/78326025-89308980-75a3-11ea-8df9-5836d4c02a7e.png)
This button moves to the next step of the process (customer address ). The button includes: 
1. Background 
2. Text 

**1. Background**
![image](https://user-images.githubusercontent.com/5694308/78326025-89308980-75a3-11ea-8df9-5836d4c02a7e.png)
Color: Secondary Color 
Corner Radius: 50 pixels 

**2. Text** 
![image](https://user-images.githubusercontent.com/5694308/78329472-ffd18500-75ab-11ea-819b-ac0f57917818.png)
Font: Color Label 
Color: On Secondary 
Emphasis: High

## 3. Divider
![image](https://user-images.githubusercontent.com/5694308/78326216-078d2b80-75a4-11ea-8e29-1dd583ffa50b.png)

This is a 328 pixel divider. 40 pixels below the input area and 40 pixels above the cart. 
Color: On Background 
Emphasis: Divider

## 4. Cart #13
This will be the component from issue #13 . The cart section will be 40 pixels below the divider and 80 pixels from the footer. 

![image](https://user-images.githubusercontent.com/5694308/78326342-59ce4c80-75a4-11ea-9c1f-7911252d83a7.png)
For the checkout process, the cart section's button will be hidden. 

## 5. Footer #12
![image](https://user-images.githubusercontent.com/5694308/78326360-62bf1e00-75a4-11ea-9c12-f44f52056bda.png)
This will be a separate issue #12 . The footer will be 80 pixels below the cart section

# Design File
For design reference, please see files in [Figma](https://www.figma.com/file/Q671pbdFk3omco20xmxk5o/foodouken.com?node-id=1245%3A57965)

**Comment by atharva3010** [comment]
Everything apart from navigation is done.
