### ISSUE TITLE
do cross browser check on browserstack

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/foodouken.com#88]
check all browsers and platforms. Note issues as a comment list here. We will break them out into separate issues and address one by one.

as an opensource project, we have unlimited testing seats. Message me your email and I will invite you:

https://www.browserstack.com/

**Comment by paulchrisluke** [comment]
as part of this testing. Please use a real iphone and andriod to test our app end to end WITHIN the facebook embed frame app. It is highly likely our audience will be coming from within facebook. Need to make sure this works well in that scenario

**Comment by kbventures** [comment]
Currently, your production environment/deployment is your master branch?

**Comment by kbventures** [comment]
I own a Pixel 3 so I can do the test on my iPhone.  Do you have an iPhone at the head office?

**Comment by paulchrisluke** [comment]
yes, master branch is to be tested, and yes we have iphones here. However, this task is in backlog (because we are not ready to start doing these checks yet). You should focus on assigned items in todo, then bugs, then backlog, in order from top down (tasks at the top of the column are more important than tasks at the bottom)

**Comment by kbventures** [comment]
This is a good resource for when we are ready to go ahead and use it:

https://www.youtube.com/watch?v=ATLrjWmHPxM
