### ISSUE TITLE
Add Footer Credit

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/foodouken.com#99]
Your mission, should you choose to accept: 

Footer credit for each individual restaurant site. 
![image](https://user-images.githubusercontent.com/5694308/79062568-b1b43400-7cc5-11ea-8657-4593ec339937.png)
![image](https://user-images.githubusercontent.com/5694308/79062599-1d969c80-7cc6-11ea-85c5-5268173d351d.png)

The design file is [here ](https://www.figma.com/file/Q671pbdFk3omco20xmxk5o/foodouken.com?node-id=1866%3A22820)

## Content 
Text: ⚡ by foodouken.com (https://patreon.com/paulchrisluke) 

## Alignment 
This is immediately below the current footer #12 
Text is centered, 32 pixel height, full width background area for both mobile and desktop

## Text Style: 
Text:
```
/* Caption */

font-family: Open Sans;
font-style: normal;
font-weight: normal;
font-size: 12px;
line-height: 16px;
```

## Color
Text: On Background Disabled (#FFFFFF 38%) 
Background: Background (#003037)

**Comment by paulchrisluke** [comment]
@kbventures the hyperlink should be linked to https://patreon.com/paulchrisluke , also the power symbol looks faded?

**Comment by kbventures** [comment]
Done.  Review requested.
